M151Projekt_Forum/forum.application/Controllers/CommentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using forum.business.Models;
using forum.business.DataAccess;
using Microsoft.AspNetCore.Authorization;

namespace forum.application.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly IDataAccess dataAccess;

        public CommentController(IDataAccess dataAccess)
        {
            this.dataAccess = dataAccess;
        }

        [Route("Comment/Index/{id:int}")]
        public IActionResult Index(int discussionId)
        {
            var comments = dataAccess.GetAllCommentsFromDiscussion(discussionId);
            return View(comments);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Comment/AddComment/{discussionId:int}")]
        public IActionResult AddComment(Comment newComment)
        {
            var user = new IdentityUser();
            user.Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            newComment.Commenter = user;
            dataAccess.CreateNewComment(newComment);
            return RedirectToAction("Details", "Discussion", new { id = newComment.DiscussionId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Comment/DeleteComment/{commentId:int}")]
        public IActionResult DeleteComment(int commentId)
        {
            
            Comment comment = dataAccess.GetCommentById(commentId);

            if (comment.Commenter.Id == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                dataAccess.DeleteComment(comment);
                return RedirectToAction("Details", "Discussion", new { id = comment.DiscussionId });
            };
            return View("Unauthorized");         
        }
    }
}

M151Projekt_Forum/forum.application/Controllers/DiscussionController.cs
using forum.business.DataAccess;
using forum.business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using forum.business;

namespace forum.application.Controllers
{
    [Authorize]
    public class DiscussionController : Controller
    {
        private readonly IDataAccess dataAccess;
        private readonly IPictureUpload pictureUpload;

        public DiscussionController(IDataAccess dataAccess, IPictureUpload pictureUpload)
        {
            this.dataAccess = dataAccess;
            this.pictureUpload = pictureUpload;
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("Discussion/Index/")]
        public IActionResult Index()
        {
            var discussions = dataAccess.GetAllDiscussions();
            return View(discussions);
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("Discussion/Details/{id:int}")]
        public IActionResult Details(int id)
        {
            var discussion = dataAccess.GetDiscussionById(id);
            discussion.Comments = dataAccess.GetAllCommentsFromDiscussion(id);
            return View("Discussion", discussion);        
        }

        [HttpGet]
        public IActionResult AddDiscussion()
        {
            return View(new Discussion());
        }

        [HttpPost]
        public async Task<IActionResult> AddDiscussion(Discussion newDiscussion, List<Microsoft.AspNetCore.Http.IFormFile> files)
        {
            var user = new IdentityUser();
            user.Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            newDiscussion.Author = user;

            newDiscussion.Pictures = await pictureUpload.UploadFile(files);

            dataAccess.CreateNewDiscussion(newDiscussion);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditDiscussion(int id) 
        {
            Discussion discussion = dataAccess.GetDiscussionById(id);
            if (discussion.Author.Id == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return View(discussion);
            }
            return RedirectToAction("Details", id);
            throw new UnauthorizedAccessException("You are not allowed to do this action");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditDiscussion(Discussion editedDiscussion)
        {
            if (editedDiscussion.Author.Id == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                dataAccess.EditDiscussion(editedDiscussion);
                return RedirectToAction("Index", editedDiscussion.Id);
            }

            return View("Unauthorized");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Discussion/DeleteDiscussion/")]
        public IActionResult DeleteDiscussion(int id)
        {
            var discussion  = dataAccess.GetDiscussionById(id);
            if (discussion.Author.Id == User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                dataAccess.DeleteDiscussion(id);
                return RedirectToAction("Index");
            };
            return View("Unauthorized");
        }
    }
}

M151Projekt_Forum/forum.application/Views/Discussion/AddDiscussion.cshtml
@model forum.business.Models.Discussion

@{
    ViewData["Title"] = "AddDiscussion";
}

<h1>AddDiscussion</h1>

<h4>Discussion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDiscussion" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pictures" class="control-label"></label>
                <input type="file" name="files" multiple />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

M151Projekt_Forum/forum.application/Views/Discussion/Discussion.cshtml
@model forum.business.Models.Discussion

@{
    ViewData["Title"] = "Discussion";
}

@Html.ActionLink("Go Back", "Index")
<h1>Discussion</h1>


@if (@User.Identity.Name == Model.Author.UserName)
{
    <div class="actions">
        @Html.ActionLink("Edit", "EditDiscussion", new { Model.Id })
        <span>&nbsp;|&nbsp;</span>
        @using (Html.BeginForm("DeleteDiscussion", "Discussion", new { Id = Model.Id }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input type="submit" class="deleteButton" value="Delete"
                   onclick="return confirm('Soll @Model.Title wirklich gelöscht werden?')" />
        }
    </div>
}
<h2>@Model.Title</h2>
<p>by @Model.Author.UserName</p>
<p>@Model.Content </p>

@foreach (forum.business.Models.Picture picture in Model.Pictures)
{
    <img src='/Files/@picture.Name' width="500" />
    <br />
    <hr />
    <br />
}

<table>
    <tr><th>Comments</th></tr>
    @{
        foreach (var comment in Model.Comments)
        {
            <tr>
                <td>
                    @comment.Content
                </td>
                <td>
                    By: @comment.Commenter.UserName
                </td>
                <td>
                    @if (comment.Commenter.UserName.Equals(User.Identity.Name))
                    {
                        <form asp-controller="Comment" asp-action="DeleteComment" asp-route-id="@comment.Id">


                            <input type="submit" value="Delete" />

                        </form>
                    }
                </td>
            </tr>
        }
    }


    <partial name="../../Views/Comment/AddComment.cshtml" model='new forum.business.Models.Comment { DiscussionId = @Model.Id }'>
</table>

M151Projekt_Forum/forum.application/Views/Discussion/EditDiscussion.cshtml
@model forum.business.Models.Discussion

@{
    ViewData["Title"] = "EditDiscussion";
}

<h1>EditDiscussion</h1>

<h4>Discussion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDiscussion">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Author.Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" value="@Model.Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" vocab="" class="form-control">@Model.Content</textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

M151Projekt_Forum/forum.application/Views/Discussion/Index.cshtml
@model List<forum.business.Models.Discussion>

@{
    @Html.ActionLink("Create new Discussion", "AddDiscussion");
    foreach (var discussion in Model)
    {
        
        if (@User.Identity.Name == discussion.Author.UserName)
        {
        <div class="actions">
             
            @Html.ActionLink("Edit", "EditDiscussion", new { id = discussion.Id})
            <span>&nbsp;|&nbsp;</span>
            @using (Html.BeginForm("DeleteDiscussion", "Discussion", new { Id = discussion.Id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <input type="submit" class="deleteButton" value="Delete"
                       onclick="return confirm('Soll @discussion.Title wirklich gelöscht werden?')" />
            }
        </div>
        }
        <a class="discussionLink" href="@Url.Action("Details", new { id = discussion.Id })">
            <div>
                <h2>
                    @discussion.Title
                </h2>
                <p>By: @discussion.Author.UserName</p>
            </div>
        </a>
        <hr />
    }
}

M151Projekt_Forum/forum.application/Views/Discussion/Unauthorized.cshtml
<h2>You are not authorized to exceute this action</h2>